name: deploy to aws
on: 
  push:
    branches: [ master ]
jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key : ${{ secrets.SSHKEY }}
        script: |
          cd /home/hubot/hackthecrisisru_chat-bot
          git pull
          /home/hubot/.nvm/versions/node/v14.2.0/bin/pm2 restart 'hubot -a telegram'
