name: deploy to aws
on: 
  push:
    branches: [ master ]
jobs:

  deploy:
    name: deploy
    runs-on: [ubuntu-16.04, ubuntu-18.04]
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key : ${{ secrets.SSHKEY }}
        script: |
          cd /home/hubot/hackthecrisisru_chat-bot
          git pull
          sudo systemctl restart annie-close-contact.service
